---
replicaCount: 2
revisionHistoryLimit: 3

modules: {}

image:
  repo: ghcr.io/japannext/oidc-exporter
  tag: ''
  pullPolicy: IfNotPresent

probe:
  additionalLabels: {}

keycloak:
  enabled: false
  endpointName: keycloak
  endpointKind: KeycloakClusterEndpoint
  realm: ""
  clientName: ""

cacertConfigMap: ""
